# Run the following script files to:

#Install Crossplane on an existing Kubernetes cluster in Google Cloude
#Create configure the Crossplane GCP Provider
#Provision a new GKE Cluster and Node Pool using Crossplane

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
    entrypoint: 'bash'
    args: 
    - '-c'
    - |
      sh dev/scripts/gcp_config.sh
      sh dev/scripts/create_gke_cluster.sh
      echo "cluster created"
      #echo "switched.. `pwd`"
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY


