substitutions:
  _PROJECT_ID: gitops-vittal
steps:   
  - name: 'gcr.io/$PROJECT_ID/envsubst'
    args: ['dev/crossplane/cluster-template.yml']
    
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash' 
    args:
    - '-c'
    - |
      gcloud container clusters get-credentials mgcp-host-crossplane-k8scluster --zone us-central1-c --project gitops-vittal
      sh dev/scripts/create_gke_cluster.sh
      echo "Customer cluster provisioned"  
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY


