# Run the following script files to:

#Install Crossplane on an existing Kubernetes cluster in Google Cloude
#Create configure the Crossplane GCP Provider
#Provision a new GKE Cluster and Node Pool using Crossplane

steps:
  - name: 'bash'
    args: 
    - '-c'
    - |
      sh dev/scripts/gcp_config.sh
      echo "gcp_config executed"
      sh dev/scripts/install_crossplane.sh
      ./install_crossplane.sh
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY


