# Run the following script files to:

#Install Crossplane on an existing Kubernetes cluster in Google Cloude
#Create configure the Crossplane GCP Provider
#Provision a new GKE Cluster and Node Pool using Crossplane

substitutions:
  _HELM_VERSION: 3.7.0
  PROJECT_ID: gitops-vittal
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
    entrypoint: 'bash'
    args: 
    - '-c'
    - |
      sh dev/scripts/gcp_config.sh
      echo "gcp_config executed"
      
#       sh dev/scripts/install_crossplane.sh
#       echo "install_crossplane executed"
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}', '--tag=gcr.io/$PROJECT_ID/helm:latest', '--build-arg', 'HELM_VERSION=v${_HELM_VERSION}', '.']
# Sanity Check: make sure basic functionality works
  - name: 'gcr.io/$PROJECT_ID/cloud-builders-helm'
 images:
  - 'gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}'
  - 'gcr.io/$PROJECT_ID/helm:latest'
tags: ['cloud-builders-community']
    entrypoint: 'bash'
    args: 
    - '-c'
    - |
      sh dev/scripts/install_crossplane.sh
      echo "install_crossplane executed"  
      
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY


