# Run the following script files to:

#Install Crossplane on an existing Kubernetes cluster in Google Cloude
#Create configure the Crossplane GCP Provider
#Provision a new GKE Cluster and Node Pool using Crossplane

steps:
  - name: 'bash'
    args: 
    - '-c'
    - |
      cd dev/scripts
      chmod +x gcp_config.sh
      echo "permission given"
      ./gcp_config.sh
      echo "gcp_config executed"
      chmod +x install_crossplane.sh
      ./install_crossplane.sh
      echo "install_crossplane executed"
      chmod +x configure_gcp_provider.sh
      ./configure_gcp_provider.sh
      echo "configure_gcp_provider executed"
      chmod +x create_gke_cluster.sh
      ./create_gke_cluster.sh
      echo "cluster created"
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY


