# Run the following script files to:

#Install Crossplane on an existing Kubernetes cluster in Google Cloude
#Create configure the Crossplane GCP Provider
#Provision a new GKE Cluster and Node Pool using Crossplane

sh dev/scripts/gcp_config.sh
sh dev/scripts/install_crossplane.sh
sh dev/dev/scripts/configure_gcp_provider.sh
sh dev/dev/create_gke_cluster.sh
